apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: jaegerdb
spec:
  version: 7.14.1
  nodeSets:
  - name: jaeger
    count: 1
    config:
      node.store.allow_mmap: false
